-- V2D2 - VSAM to DB2 Conversion System
-- Database schema for z/OS DB2 v7
-- ============================================================

CREATE DATABASE V2D2DB;
CREATE TABLESPACE V2D2TS IN V2D2DB USING STOGROUP SYSDEFLT
  PRIQTY 2880 SECQTY 720 LOCKSIZE PAGE;

-- Jobs de conversion
CREATE TABLE IBMUSER.V2D2_JOBS (
  JOB_ID      INTEGER NOT NULL,
  SOURCE_DSN  CHAR(44),
  MEMBER      CHAR(8),
  STATUS      CHAR(1),         -- A=analyzing P=pending C=converted X=compiled E=error
  VSAM_COUNT  SMALLINT,
  CREATED_TS  CHAR(26),
  PRIMARY KEY (JOB_ID)
) IN V2D2DB.V2D2TS;

-- Archivos VSAM encontrados
CREATE TABLE IBMUSER.V2D2_FILES (
  JOB_ID      INTEGER NOT NULL,
  FILE_NAME   CHAR(30) NOT NULL,
  FILE_ORG    CHAR(4),         -- KSDS/ESDS/RRDS
  KEY_FIELD   CHAR(30),
  REC_LEN     SMALLINT,
  REDEF_COUNT SMALLINT,
  TABLE_NAME  CHAR(44),
  PRIMARY KEY (JOB_ID, FILE_NAME)
) IN V2D2DB.V2D2TS;

-- Campos del FD
CREATE TABLE IBMUSER.V2D2_FIELDS (
  JOB_ID      INTEGER NOT NULL,
  FILE_NAME   CHAR(30) NOT NULL,
  FIELD_NAME  CHAR(30) NOT NULL,
  LEVEL_NUM   SMALLINT,
  PIC_CLAUSE  CHAR(30),
  USAGE_TYPE  CHAR(10),        -- DISPLAY/COMP/COMP-3
  FIELD_LEN   SMALLINT,
  REDEF_OF    CHAR(30),        -- nombre del campo que redefine
  REDEF_GROUP CHAR(1),         -- A, B, C... para distinguir variantes
  DB2_TYPE    CHAR(30),        -- tipo DB2 generado
  DB2_COLNAME CHAR(30),
  OFFSET_POS  SMALLINT,
  PRIMARY KEY (JOB_ID, FILE_NAME, FIELD_NAME)
) IN V2D2DB.V2D2TS;

-- Operaciones VSAM encontradas
CREATE TABLE IBMUSER.V2D2_OPS (
  JOB_ID      INTEGER NOT NULL,
  LINE_NUM    INTEGER NOT NULL,
  OP_TYPE     CHAR(10),        -- READ/WRITE/REWRITE/DELETE/STARTBR/READNEXT/ENDBR
  FILE_NAME   CHAR(30),
  IS_CICS     CHAR(1),         -- Y/N
  SOURCE_LINE CHAR(72),
  PRIMARY KEY (JOB_ID, LINE_NUM)
) IN V2D2DB.V2D2TS;

-- Log de conversion
CREATE TABLE IBMUSER.V2D2_LOG (
  JOB_ID      INTEGER NOT NULL,
  SEQ_NUM     INTEGER NOT NULL,
  MSG_TYPE    CHAR(1),         -- I=info W=warning E=error
  MESSAGE     CHAR(80),
  PRIMARY KEY (JOB_ID, SEQ_NUM)
) IN V2D2DB.V2D2TS;
